#ArangoDB
arangodb: 
  hosts: 10.200.1.183:8529,10.200.1.181:8529,10.200.1.184:8529
  user: root
  password: root
  database: _system
  protocol: HTTP_JSON  #默认VST VST,HTTP_JSON,HTTP_VPACK
  useSsl: false #使用ssl  默认false
#spark配置
spark: 
  master: local #spark://10.200.1.193:7077    #local
  appName: SparkTest
  executor.memory: 4g
  scheduler.mode: FAIR
  cores.max: 6
  deploy.defaultCores: 2
  logLevel: WARN
#配置日志
logging: 
  config: classpath:logback-boot.xml #引入日志配置文件